[package]
name = "dirchop"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tar = "0.4.40"
clap = { version = "4.5.1", features = ["cargo"] }
anyhow = "1.0.80"
